// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

/**
 * Item in *Footer → Social Links*
 */
export interface FooterDocumentDataSocialLinksItem {
  /**
   * Icon field in *Footer → Social Links*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.social_links[].icon
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  icon: prismic.ImageField<never>;

  /**
   * Link field in *Footer → Social Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Enter link to social
   * - **API ID Path**: footer.social_links[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Item in *Footer → Contacts*
 */
export interface FooterDocumentDataContactsItem {
  /**
   * Label field in *Footer → Contacts*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.contacts[].label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  label: prismic.KeyTextField;

  /**
   * Contact Value field in *Footer → Contacts*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.contacts[].contact_value
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  contact_value: prismic.KeyTextField;
}

/**
 * Item in *Footer → Navigations*
 */
export interface FooterDocumentDataNavigationsItem {
  /**
   * Link Item field in *Footer → Navigations*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Enter parent link
   * - **API ID Path**: footer.navigations[].link_item
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link_item: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Sub Link Items field in *Footer → Navigations*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.navigations[].sublink_items
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  sublink_items: prismic.Repeatable<
    prismic.LinkField<string, string, unknown, prismic.FieldState, never>
  >;
}

/**
 * Content for Footer documents
 */
interface FooterDocumentData {
  /**
   * Logo field in *Footer*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  logo: prismic.ImageField<never>;

  /**
   * Social Links field in *Footer*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.social_links[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  social_links: prismic.GroupField<Simplify<FooterDocumentDataSocialLinksItem>>;

  /**
   * Primary CTA field in *Footer*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Add your action
   * - **API ID Path**: footer.primary_cta
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  primary_cta: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Contact Label field in *Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter label
   * - **API ID Path**: footer.contact_label
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  contact_label: prismic.KeyTextField;

  /**
   * Contacts field in *Footer*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.contacts[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  contacts: prismic.GroupField<Simplify<FooterDocumentDataContactsItem>>;

  /**
   * Navigation Label field in *Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter label
   * - **API ID Path**: footer.navigation_label
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  navigation_label: prismic.KeyTextField;

  /**
   * Navigations field in *Footer*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.navigations[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  navigations: prismic.GroupField<Simplify<FooterDocumentDataNavigationsItem>>;

  /**
   * Copyright Text field in *Footer*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.copyright_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  copyright_text: prismic.RichTextField;
}

/**
 * Footer document from Prismic
 *
 * - **API ID**: `footer`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FooterDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<FooterDocumentData>,
    "footer",
    Lang
  >;

/**
 * Item in *Header → Navigations*
 */
export interface HeaderDocumentDataNavigationsItem {
  /**
   * Navigation Item field in *Header → Navigations*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: header.navigations[].link_item
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link_item: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Navigation Sub Items field in *Header → Navigations*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Add your link item
   * - **API ID Path**: header.navigations[].navigation_sub_items
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  navigation_sub_items: prismic.Repeatable<
    prismic.LinkField<string, string, unknown, prismic.FieldState, never>
  >;
}

/**
 * Item in *Header → CTA Buttons*
 */
export interface HeaderDocumentDataCtaButtonsItem {
  /**
   * Button field in *Header → CTA Buttons*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Add your actions
   * - **API ID Path**: header.cta_buttons[].button
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  button: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Content for Header documents
 */
interface HeaderDocumentData {
  /**
   * Logo field in *Header*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: header.logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  logo: prismic.ImageField<never>;

  /**
   * Navigations field in *Header*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: header.navigations[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  navigations: prismic.GroupField<Simplify<HeaderDocumentDataNavigationsItem>>;

  /**
   * CTA Buttons field in *Header*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: header.cta_buttons[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  cta_buttons: prismic.GroupField<Simplify<HeaderDocumentDataCtaButtonsItem>>;
}

/**
 * Header document from Prismic
 *
 * - **API ID**: `header`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HeaderDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HeaderDocumentData>,
    "header",
    Lang
  >;

type PageDocumentDataSlicesSlice =
  | OfficeGallerySlice
  | TestimonialSlice
  | QualityCareMessageSlice
  | LargeImageSlice
  | ServicesGridSlice
  | CertificationsSlice
  | DentalHeroSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice>; /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

export type AllDocumentTypes = FooterDocument | HeaderDocument | PageDocument;

/**
 * Item in *Certifications → Default → Primary → Certifications*
 */
export interface CertificationsSliceDefaultPrimaryCertificationsItem {
  /**
   * Logo or Badge Image field in *Certifications → Default → Primary → Certifications*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: certifications.default.primary.certifications[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Label field in *Certifications → Default → Primary → Certifications*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Optional caption or description
   * - **API ID Path**: certifications.default.primary.certifications[].label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  label: prismic.KeyTextField;
}

/**
 * Primary content in *Certifications → Default → Primary*
 */
export interface CertificationsSliceDefaultPrimary {
  /**
   * Certifications field in *Certifications → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: certifications.default.primary.certifications[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  certifications: prismic.GroupField<
    Simplify<CertificationsSliceDefaultPrimaryCertificationsItem>
  >;
}

/**
 * Default variation for Certifications Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default variation
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CertificationsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CertificationsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Certifications*
 */
type CertificationsSliceVariation = CertificationsSliceDefault;

/**
 * Certifications Shared Slice
 *
 * - **API ID**: `certifications`
 * - **Description**: Grid layout for certification logos and badges
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CertificationsSlice = prismic.SharedSlice<
  "certifications",
  CertificationsSliceVariation
>;

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface DentalHeroSliceDefaultPrimary {
  /**
   * Tagline field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: e.g., CREATING SMILES,
   * - **API ID Path**: dental_hero.default.primary.tagline
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  tagline: prismic.KeyTextField;

  /**
   * Heading field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: e.g., Transforming Lives
   * - **API ID Path**: dental_hero.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Description field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Enter description text...
   * - **API ID Path**: dental_hero.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Button Link field in *Hero → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: dental_hero.default.primary.buttonLink
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  buttonLink: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Background Image field in *Hero → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: dental_hero.default.primary.backgroundImage
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  backgroundImage: prismic.ImageField<never>;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default dental hero variation
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type DentalHeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<DentalHeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type DentalHeroSliceVariation = DentalHeroSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `dental_hero`
 * - **Description**: A dental practice hero section with tagline, heading, description, and call-to-action button
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type DentalHeroSlice = prismic.SharedSlice<
  "dental_hero",
  DentalHeroSliceVariation
>;

/**
 * Primary content in *LargeImage → Default → Primary*
 */
export interface LargeImageSliceDefaultPrimary {
  /**
   * Image field in *LargeImage → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: large_image.default.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for LargeImage Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type LargeImageSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<LargeImageSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *LargeImage*
 */
type LargeImageSliceVariation = LargeImageSliceDefault;

/**
 * LargeImage Shared Slice
 *
 * - **API ID**: `large_image`
 * - **Description**: LargeImage
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type LargeImageSlice = prismic.SharedSlice<
  "large_image",
  LargeImageSliceVariation
>;

/**
 * Item in *OfficeGallery → Default → Primary → Gallery Images*
 */
export interface OfficeGallerySliceDefaultPrimaryGalleryImagesItem {
  /**
   * Image field in *OfficeGallery → Default → Primary → Gallery Images*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: office_gallery.default.primary.gallery_images[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;
}

/**
 * Primary content in *OfficeGallery → Default → Primary*
 */
export interface OfficeGallerySliceDefaultPrimary {
  /**
   * Title field in *OfficeGallery → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: office_gallery.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Gallery Images field in *OfficeGallery → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: office_gallery.default.primary.gallery_images[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  gallery_images: prismic.GroupField<
    Simplify<OfficeGallerySliceDefaultPrimaryGalleryImagesItem>
  >;

  /**
   * Center Logo field in *OfficeGallery → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: office_gallery.default.primary.center_logo
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  center_logo: prismic.ImageField<never>;
}

/**
 * Default variation for OfficeGallery Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default variation with office gallery
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type OfficeGallerySliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<OfficeGallerySliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *OfficeGallery*
 */
type OfficeGallerySliceVariation = OfficeGallerySliceDefault;

/**
 * OfficeGallery Shared Slice
 *
 * - **API ID**: `office_gallery`
 * - **Description**: A gallery of office images with a title and centered branding element
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type OfficeGallerySlice = prismic.SharedSlice<
  "office_gallery",
  OfficeGallerySliceVariation
>;

/**
 * Primary content in *MessageSection → Default → Primary*
 */
export interface QualityCareMessageSliceDefaultPrimary {
  /**
   * Heading field in *MessageSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Enter heading
   * - **API ID Path**: quality_care_message.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Description field in *MessageSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Enter description
   * - **API ID Path**: quality_care_message.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;
}

/**
 * Default variation for MessageSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default variation
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type QualityCareMessageSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<QualityCareMessageSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *MessageSection*
 */
type QualityCareMessageSliceVariation = QualityCareMessageSliceDefault;

/**
 * MessageSection Shared Slice
 *
 * - **API ID**: `quality_care_message`
 * - **Description**: A quality care message section with heading and description
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type QualityCareMessageSlice = prismic.SharedSlice<
  "quality_care_message",
  QualityCareMessageSliceVariation
>;

/**
 * Item in *ServicesGrid → Default → Primary → Services*
 */
export interface ServicesGridSliceDefaultPrimaryServicesItem {
  /**
   * Icon field in *ServicesGrid → Default → Primary → Services*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: services_grid.default.primary.services[].icon
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  icon: prismic.ImageField<never>;

  /**
   * Service Title field in *ServicesGrid → Default → Primary → Services*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: services_grid.default.primary.services[].title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Learn More Link field in *ServicesGrid → Default → Primary → Services*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: services_grid.default.primary.services[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Primary content in *ServicesGrid → Default → Primary*
 */
export interface ServicesGridSliceDefaultPrimary {
  /**
   * Heading field in *ServicesGrid → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: services_grid.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Services field in *ServicesGrid → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: services_grid.default.primary.services[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  services: prismic.GroupField<
    Simplify<ServicesGridSliceDefaultPrimaryServicesItem>
  >;

  /**
   * CTA Button field in *ServicesGrid → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: services_grid.default.primary.cta_button
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  cta_button: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Default variation for ServicesGrid Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default variation
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ServicesGridSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ServicesGridSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ServicesGrid*
 */
type ServicesGridSliceVariation = ServicesGridSliceDefault;

/**
 * ServicesGrid Shared Slice
 *
 * - **API ID**: `services_grid`
 * - **Description**: A grid of services with heading, service cards, and CTA button
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ServicesGridSlice = prismic.SharedSlice<
  "services_grid",
  ServicesGridSliceVariation
>;

/**
 * Item in *Testimonial → Default → Primary → Testimonials*
 */
export interface TestimonialSliceDefaultPrimaryTestimonialsItem {
  /**
   * Title field in *Testimonial → Default → Primary → Testimonials*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial.default.primary.testimonials[].title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Review Content field in *Testimonial → Default → Primary → Testimonials*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial.default.primary.testimonials[].review_content
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  review_content: prismic.RichTextField;

  /**
   * Reviewer Name field in *Testimonial → Default → Primary → Testimonials*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial.default.primary.testimonials[].reviewer_name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  reviewer_name: prismic.KeyTextField;

  /**
   * Reviewer Image field in *Testimonial → Default → Primary → Testimonials*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial.default.primary.testimonials[].reviewer_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  reviewer_image: prismic.ImageField<never>;
}

/**
 * Primary content in *Testimonial → Default → Primary*
 */
export interface TestimonialSliceDefaultPrimary {
  /**
   * Testimonials field in *Testimonial → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial.default.primary.testimonials[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  testimonials: prismic.GroupField<
    Simplify<TestimonialSliceDefaultPrimaryTestimonialsItem>
  >;

  /**
   * View More Action field in *Testimonial → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial.default.primary.view_more_action
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  view_more_action: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Default variation for Testimonial Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default testimonial variation
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TestimonialSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TestimonialSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Testimonial*
 */
type TestimonialSliceVariation = TestimonialSliceDefault;

/**
 * Testimonial Shared Slice
 *
 * - **API ID**: `testimonial`
 * - **Description**: Customer testimonial section with image, review text, and call-to-action
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TestimonialSlice = prismic.SharedSlice<
  "testimonial",
  TestimonialSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      FooterDocument,
      FooterDocumentData,
      FooterDocumentDataSocialLinksItem,
      FooterDocumentDataContactsItem,
      FooterDocumentDataNavigationsItem,
      HeaderDocument,
      HeaderDocumentData,
      HeaderDocumentDataNavigationsItem,
      HeaderDocumentDataCtaButtonsItem,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      AllDocumentTypes,
      CertificationsSlice,
      CertificationsSliceDefaultPrimaryCertificationsItem,
      CertificationsSliceDefaultPrimary,
      CertificationsSliceVariation,
      CertificationsSliceDefault,
      DentalHeroSlice,
      DentalHeroSliceDefaultPrimary,
      DentalHeroSliceVariation,
      DentalHeroSliceDefault,
      LargeImageSlice,
      LargeImageSliceDefaultPrimary,
      LargeImageSliceVariation,
      LargeImageSliceDefault,
      OfficeGallerySlice,
      OfficeGallerySliceDefaultPrimaryGalleryImagesItem,
      OfficeGallerySliceDefaultPrimary,
      OfficeGallerySliceVariation,
      OfficeGallerySliceDefault,
      QualityCareMessageSlice,
      QualityCareMessageSliceDefaultPrimary,
      QualityCareMessageSliceVariation,
      QualityCareMessageSliceDefault,
      ServicesGridSlice,
      ServicesGridSliceDefaultPrimaryServicesItem,
      ServicesGridSliceDefaultPrimary,
      ServicesGridSliceVariation,
      ServicesGridSliceDefault,
      TestimonialSlice,
      TestimonialSliceDefaultPrimaryTestimonialsItem,
      TestimonialSliceDefaultPrimary,
      TestimonialSliceVariation,
      TestimonialSliceDefault,
    };
  }
}
