// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

/**
 * Item in *Footer → Social Links*
 */
export interface FooterDocumentDataSocialLinksItem {
  /**
   * Icon field in *Footer → Social Links*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.social_links[].icon
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  icon: prismic.ImageField<never>;

  /**
   * Link field in *Footer → Social Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Enter link to social
   * - **API ID Path**: footer.social_links[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Item in *Footer → Contacts*
 */
export interface FooterDocumentDataContactsItem {
  /**
   * Label field in *Footer → Contacts*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.contacts[].label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  label: prismic.KeyTextField;

  /**
   * Contact Value field in *Footer → Contacts*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.contacts[].contact_value
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  contact_value: prismic.KeyTextField;
}

/**
 * Item in *Footer → Navigations*
 */
export interface FooterDocumentDataNavigationsItem {
  /**
   * Link Item field in *Footer → Navigations*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Enter parent link
   * - **API ID Path**: footer.navigations[].link_item
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link_item: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Sub Link Items field in *Footer → Navigations*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.navigations[].sublink_items
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  sublink_items: prismic.Repeatable<
    prismic.LinkField<string, string, unknown, prismic.FieldState, never>
  >;
}

/**
 * Item in *Footer → Office hours*
 */
export interface FooterDocumentDataOfficeHoursItem {
  /**
   * Open time field in *Footer → Office hours*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.office_hours[].open_time
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  open_time: prismic.KeyTextField;

  /**
   * Close time field in *Footer → Office hours*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.office_hours[].close_time
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  close_time: prismic.KeyTextField;

  /**
   * Day field in *Footer → Office hours*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.office_hours[].day
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  day: prismic.SelectField<
    | "Monday"
    | "Tuesday"
    | "Wednesday"
    | "Thursday"
    | "Friday"
    | "Saturday"
    | "Sunday"
  >;

  /**
   * Is Closed field in *Footer → Office hours*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: footer.office_hours[].is_closed
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  is_closed: prismic.BooleanField;
}

/**
 * Item in *Footer → Top Footer Contacts*
 */
export interface FooterDocumentDataTopFooterContactsItem {
  /**
   * Icon field in *Footer → Top Footer Contacts*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.top_footer_contacts[].icon
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  icon: prismic.ImageField<never>;

  /**
   * Label field in *Footer → Top Footer Contacts*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.top_footer_contacts[].label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  label: prismic.KeyTextField;

  /**
   * Value field in *Footer → Top Footer Contacts*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.top_footer_contacts[].value
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  value: prismic.KeyTextField;
}

/**
 * Content for Footer documents
 */
interface FooterDocumentData {
  /**
   * Logo field in *Footer*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  logo: prismic.ImageField<never>;

  /**
   * Social Links field in *Footer*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.social_links[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  social_links: prismic.GroupField<Simplify<FooterDocumentDataSocialLinksItem>>;

  /**
   * Primary CTA field in *Footer*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Add your action
   * - **API ID Path**: footer.primary_cta
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  primary_cta: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Contact Label field in *Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter label
   * - **API ID Path**: footer.contact_label
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  contact_label: prismic.KeyTextField;

  /**
   * Contacts field in *Footer*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.contacts[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  contacts: prismic.GroupField<Simplify<FooterDocumentDataContactsItem>>;

  /**
   * Navigation Label field in *Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter label
   * - **API ID Path**: footer.navigation_label
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  navigation_label: prismic.KeyTextField;

  /**
   * Navigations field in *Footer*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.navigations[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  navigations: prismic.GroupField<Simplify<FooterDocumentDataNavigationsItem>>;

  /**
   * Copyright Text field in *Footer*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.copyright_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  copyright_text: prismic.RichTextField;

  /**
   * Clinic name field in *Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.clinic_name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  clinic_name: prismic.KeyTextField;

  /**
   * Secondary CTA field in *Footer*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.secondary_cta
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  secondary_cta: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Office hours icon field in *Footer*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.office_hours_icon
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  office_hours_icon: prismic.ImageField<never>;

  /**
   * Office hours label field in *Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.office_hours_label
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  office_hours_label: prismic.KeyTextField;

  /**
   * Office hours field in *Footer*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.office_hours[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  office_hours: prismic.GroupField<Simplify<FooterDocumentDataOfficeHoursItem>>;

  /**
   * Map location field in *Footer*
   *
   * - **Field Type**: GeoPoint
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.map_location
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/geopoint
   */
  map_location: prismic.GeoPointField;

  /**
   * Top Footer Contacts field in *Footer*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.top_footer_contacts[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  top_footer_contacts: prismic.GroupField<
    Simplify<FooterDocumentDataTopFooterContactsItem>
  >;
}

/**
 * Footer document from Prismic
 *
 * - **API ID**: `footer`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FooterDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<FooterDocumentData>,
    "footer",
    Lang
  >;

/**
 * Item in *Header → Navigations*
 */
export interface HeaderDocumentDataNavigationsItem {
  /**
   * Navigation Item field in *Header → Navigations*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: header.navigations[].link_item
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link_item: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Navigation Sub Items field in *Header → Navigations*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Add your link item
   * - **API ID Path**: header.navigations[].navigation_sub_items
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  navigation_sub_items: prismic.Repeatable<
    prismic.LinkField<string, string, unknown, prismic.FieldState, never>
  >;
}

/**
 * Item in *Header → CTA Buttons*
 */
export interface HeaderDocumentDataCtaButtonsItem {
  /**
   * Button field in *Header → CTA Buttons*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Add your actions
   * - **API ID Path**: header.cta_buttons[].button
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  button: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Content for Header documents
 */
interface HeaderDocumentData {
  /**
   * Logo field in *Header*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: header.logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  logo: prismic.ImageField<never>;

  /**
   * Navigations field in *Header*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: header.navigations[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  navigations: prismic.GroupField<Simplify<HeaderDocumentDataNavigationsItem>>;

  /**
   * CTA Buttons field in *Header*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: header.cta_buttons[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  cta_buttons: prismic.GroupField<Simplify<HeaderDocumentDataCtaButtonsItem>>;
}

/**
 * Header document from Prismic
 *
 * - **API ID**: `header`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HeaderDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HeaderDocumentData>,
    "header",
    Lang
  >;

type PageDocumentDataSlicesSlice =
  | TreatmentShowcaseSlice
  | VideoCarouselSlice
  | SmileCalloutSlice
  | ServiceCardSlice
  | DentalImplantGuideSlice
  | ReviewsGridSlice
  | ReviewsCtaSlice
  | PatientStoriesSlice
  | PatientInformationSlice
  | MembershipPlansSlice
  | ConsultationCtaSlice
  | CaseShowcaseSlice
  | DoctorProfileSlice
  | TeamSectionSlice
  | OfficeGallerySlice
  | TestimonialSlice
  | QualityCareMessageSlice
  | LargeImageSlice
  | ServicesGridSlice
  | CertificationsSlice
  | DentalHeroSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice>; /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

export type AllDocumentTypes = FooterDocument | HeaderDocument | PageDocument;

/**
 * Item in *CaseShowcase → Default → Primary → Cases*
 */
export interface CaseShowcaseSliceDefaultPrimaryCasesItem {
  /**
   * Image field in *CaseShowcase → Default → Primary → Cases*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: case_showcase.default.primary.cases[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;
}

/**
 * Primary content in *CaseShowcase → Default → Primary*
 */
export interface CaseShowcaseSliceDefaultPrimary {
  /**
   * Cases field in *CaseShowcase → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: case_showcase.default.primary.cases[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  cases: prismic.GroupField<Simplify<CaseShowcaseSliceDefaultPrimaryCasesItem>>;
}

/**
 * Default variation for CaseShowcase Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default variation with cases grid
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CaseShowcaseSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CaseShowcaseSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *CaseShowcase*
 */
type CaseShowcaseSliceVariation = CaseShowcaseSliceDefault;

/**
 * CaseShowcase Shared Slice
 *
 * - **API ID**: `case_showcase`
 * - **Description**: A grid showcase of dental cases displaying before and after treatment results
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CaseShowcaseSlice = prismic.SharedSlice<
  "case_showcase",
  CaseShowcaseSliceVariation
>;

/**
 * Item in *Certifications → Default → Primary → Certifications*
 */
export interface CertificationsSliceDefaultPrimaryCertificationsItem {
  /**
   * Logo or Badge Image field in *Certifications → Default → Primary → Certifications*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: certifications.default.primary.certifications[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Label field in *Certifications → Default → Primary → Certifications*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Optional caption or description
   * - **API ID Path**: certifications.default.primary.certifications[].label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  label: prismic.KeyTextField;
}

/**
 * Primary content in *Certifications → Default → Primary*
 */
export interface CertificationsSliceDefaultPrimary {
  /**
   * Certifications field in *Certifications → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: certifications.default.primary.certifications[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  certifications: prismic.GroupField<
    Simplify<CertificationsSliceDefaultPrimaryCertificationsItem>
  >;
}

/**
 * Default variation for Certifications Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default variation
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CertificationsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CertificationsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Certifications*
 */
type CertificationsSliceVariation = CertificationsSliceDefault;

/**
 * Certifications Shared Slice
 *
 * - **API ID**: `certifications`
 * - **Description**: Grid layout for certification logos and badges
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CertificationsSlice = prismic.SharedSlice<
  "certifications",
  CertificationsSliceVariation
>;

/**
 * Item in *ConsultationCTA → Default → Primary → Contacts*
 */
export interface ConsultationCtaSliceDefaultPrimaryContactsItem {
  /**
   * Label field in *ConsultationCTA → Default → Primary → Contacts*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: consultation_cta.default.primary.contacts[].label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  label: prismic.KeyTextField;

  /**
   * Value field in *ConsultationCTA → Default → Primary → Contacts*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: consultation_cta.default.primary.contacts[].value
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  value: prismic.KeyTextField;
}

/**
 * Item in *ConsultationCTA → Default → Primary → Office Hours*
 */
export interface ConsultationCtaSliceDefaultPrimaryOfficeHoursItem {
  /**
   * Day field in *ConsultationCTA → Default → Primary → Office Hours*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Monday
   * - **API ID Path**: consultation_cta.default.primary.office_hours[].day
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  day: prismic.KeyTextField;

  /**
   * Hours field in *ConsultationCTA → Default → Primary → Office Hours*
   *
   * - **Field Type**: Text
   * - **Placeholder**: 9:00 AM - 5:00 PM
   * - **API ID Path**: consultation_cta.default.primary.office_hours[].hours
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  hours: prismic.KeyTextField;
}

/**
 * Primary content in *ConsultationCTA → Default → Primary*
 */
export interface ConsultationCtaSliceDefaultPrimary {
  /**
   * Heading field in *ConsultationCTA → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Schedule Your Consultation Today
   * - **API ID Path**: consultation_cta.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Office Name field in *ConsultationCTA → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Advanced Dentistry & Implant Center
   * - **API ID Path**: consultation_cta.default.primary.office_name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  office_name: prismic.KeyTextField;

  /**
   * Office Location field in *ConsultationCTA → Default → Primary*
   *
   * - **Field Type**: GeoPoint
   * - **Placeholder**: *None*
   * - **API ID Path**: consultation_cta.default.primary.office_location
   * - **Documentation**: https://prismic.io/docs/fields/geopoint
   */
  office_location: prismic.GeoPointField;

  /**
   * Contacts field in *ConsultationCTA → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: consultation_cta.default.primary.contacts[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  contacts: prismic.GroupField<
    Simplify<ConsultationCtaSliceDefaultPrimaryContactsItem>
  >;

  /**
   * Office Hours field in *ConsultationCTA → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: consultation_cta.default.primary.office_hours[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  office_hours: prismic.GroupField<
    Simplify<ConsultationCtaSliceDefaultPrimaryOfficeHoursItem>
  >;

  /**
   * Button Text field in *ConsultationCTA → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: consultation_cta.default.primary.button_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  button_text: prismic.KeyTextField;

  /**
   * Form Type field in *ConsultationCTA → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: consultation_cta.default.primary.form_type
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  form_type: prismic.SelectField<
    "consultation" | "appointment" | "get_in_touch"
  >;
}

/**
 * Default variation for ConsultationCTA Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default variation
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ConsultationCtaSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ConsultationCtaSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ConsultationCTA*
 */
type ConsultationCtaSliceVariation = ConsultationCtaSliceDefault;

/**
 * ConsultationCTA Shared Slice
 *
 * - **API ID**: `consultation_cta`
 * - **Description**: A consultation scheduling section with contact form and office information
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ConsultationCtaSlice = prismic.SharedSlice<
  "consultation_cta",
  ConsultationCtaSliceVariation
>;

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface DentalHeroSliceDefaultPrimary {
  /**
   * Tagline field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: e.g., CREATING SMILES,
   * - **API ID Path**: dental_hero.default.primary.tagline
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  tagline: prismic.KeyTextField;

  /**
   * Heading field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: e.g., Transforming Lives
   * - **API ID Path**: dental_hero.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Description field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Enter description text...
   * - **API ID Path**: dental_hero.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Button Link field in *Hero → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: dental_hero.default.primary.buttonLink
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  buttonLink: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Background Image field in *Hero → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: dental_hero.default.primary.backgroundImage
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  backgroundImage: prismic.ImageField<never>;

  /**
   * With overlay field in *Hero → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: dental_hero.default.primary.with_overlay
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  with_overlay: prismic.BooleanField;

  /**
   * Reverse Tagline field in *Hero → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: dental_hero.default.primary.reverse_tagline
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  reverse_tagline: prismic.BooleanField;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default dental hero variation
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type DentalHeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<DentalHeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type DentalHeroSliceVariation = DentalHeroSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `dental_hero`
 * - **Description**: A dental practice hero section with tagline, heading, description, and call-to-action button
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type DentalHeroSlice = prismic.SharedSlice<
  "dental_hero",
  DentalHeroSliceVariation
>;

/**
 * Primary content in *RichTextSection → Default → Primary*
 */
export interface DentalImplantGuideSliceDefaultPrimary {
  /**
   * Title field in *RichTextSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: dental_implant_guide.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Content field in *RichTextSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: dental_implant_guide.default.primary.content
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  content: prismic.RichTextField;

  /**
   * Background Color field in *RichTextSection → Default → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: dental_implant_guide.default.primary.background_color
   * - **Documentation**: https://prismic.io/docs/fields/color
   */
  background_color: prismic.ColorField;
}

/**
 * Default variation for RichTextSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default variation with repeating dental implant guide sections
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type DentalImplantGuideSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<DentalImplantGuideSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *RichTextSection*
 */
type DentalImplantGuideSliceVariation = DentalImplantGuideSliceDefault;

/**
 * RichTextSection Shared Slice
 *
 * - **API ID**: `dental_implant_guide`
 * - **Description**: A guide section showcasing dental implant information with repeating sections containing title, description, and image
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type DentalImplantGuideSlice = prismic.SharedSlice<
  "dental_implant_guide",
  DentalImplantGuideSliceVariation
>;

/**
 * Primary content in *DoctorProfile → Default → Primary*
 */
export interface DoctorProfileSliceDefaultPrimary {
  /**
   * Title field in *DoctorProfile → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Meet The Doctor
   * - **API ID Path**: doctor_profile.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Doctor Image field in *DoctorProfile → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: doctor_profile.default.primary.doctor_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  doctor_image: prismic.ImageField<never>;

  /**
   * Doctor Name field in *DoctorProfile → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: doctor_profile.default.primary.doctor_name
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  doctor_name: prismic.RichTextField;

  /**
   * Biography field in *DoctorProfile → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: doctor_profile.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;
}

/**
 * Default variation for DoctorProfile Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default doctor profile variation
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type DoctorProfileSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<DoctorProfileSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *DoctorProfile*
 */
type DoctorProfileSliceVariation = DoctorProfileSliceDefault;

/**
 * DoctorProfile Shared Slice
 *
 * - **API ID**: `doctor_profile`
 * - **Description**: Doctor profile section with image, name, credentials, and biography
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type DoctorProfileSlice = prismic.SharedSlice<
  "doctor_profile",
  DoctorProfileSliceVariation
>;

/**
 * Primary content in *LargeImage → Default → Primary*
 */
export interface LargeImageSliceDefaultPrimary {
  /**
   * Image field in *LargeImage → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: large_image.default.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for LargeImage Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type LargeImageSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<LargeImageSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *LargeImage*
 */
type LargeImageSliceVariation = LargeImageSliceDefault;

/**
 * LargeImage Shared Slice
 *
 * - **API ID**: `large_image`
 * - **Description**: LargeImage
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type LargeImageSlice = prismic.SharedSlice<
  "large_image",
  LargeImageSliceVariation
>;

/**
 * Item in *MembershipPlans → Default → Primary → Membership Plans*
 */
export interface MembershipPlansSliceDefaultPrimaryPlansItem {
  /**
   * Plan Name field in *MembershipPlans → Default → Primary → Membership Plans*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: membership_plans.default.primary.plans[].planName
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  planName: prismic.KeyTextField;

  /**
   * Price field in *MembershipPlans → Default → Primary → Membership Plans*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: membership_plans.default.primary.plans[].price
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  price: prismic.KeyTextField;

  /**
   * Features List field in *MembershipPlans → Default → Primary → Membership Plans*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: membership_plans.default.primary.plans[].features
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  features: prismic.RichTextField;
}

/**
 * Primary content in *MembershipPlans → Default → Primary*
 */
export interface MembershipPlansSliceDefaultPrimary {
  /**
   * Main Heading field in *MembershipPlans → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: membership_plans.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Membership Plans field in *MembershipPlans → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: membership_plans.default.primary.plans[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  plans: prismic.GroupField<
    Simplify<MembershipPlansSliceDefaultPrimaryPlansItem>
  >;

  /**
   * Promotional Text field in *MembershipPlans → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: membership_plans.default.primary.promotionalText
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  promotionalText: prismic.RichTextField;

  /**
   * How It Works field in *MembershipPlans → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: membership_plans.default.primary.howItWorks
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  howItWorks: prismic.RichTextField;
}

/**
 * Default variation for MembershipPlans Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default variation displaying membership plans with terms
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type MembershipPlansSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<MembershipPlansSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *MembershipPlans*
 */
type MembershipPlansSliceVariation = MembershipPlansSliceDefault;

/**
 * MembershipPlans Shared Slice
 *
 * - **API ID**: `membership_plans`
 * - **Description**: A membership plans section displaying pricing tiers with features and membership terms information
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type MembershipPlansSlice = prismic.SharedSlice<
  "membership_plans",
  MembershipPlansSliceVariation
>;

/**
 * Item in *OfficeGallery → Default → Primary → Gallery Images*
 */
export interface OfficeGallerySliceDefaultPrimaryGalleryImagesItem {
  /**
   * Image field in *OfficeGallery → Default → Primary → Gallery Images*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: office_gallery.default.primary.gallery_images[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;
}

/**
 * Primary content in *OfficeGallery → Default → Primary*
 */
export interface OfficeGallerySliceDefaultPrimary {
  /**
   * Title field in *OfficeGallery → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: office_gallery.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Gallery Images field in *OfficeGallery → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: office_gallery.default.primary.gallery_images[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  gallery_images: prismic.GroupField<
    Simplify<OfficeGallerySliceDefaultPrimaryGalleryImagesItem>
  >;

  /**
   * Center Logo field in *OfficeGallery → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: office_gallery.default.primary.center_logo
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  center_logo: prismic.ImageField<never>;
}

/**
 * Default variation for OfficeGallery Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default variation with office gallery
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type OfficeGallerySliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<OfficeGallerySliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *OfficeGallery*
 */
type OfficeGallerySliceVariation = OfficeGallerySliceDefault;

/**
 * OfficeGallery Shared Slice
 *
 * - **API ID**: `office_gallery`
 * - **Description**: A gallery of office images with a title and centered branding element
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type OfficeGallerySlice = prismic.SharedSlice<
  "office_gallery",
  OfficeGallerySliceVariation
>;

/**
 * Primary content in *PatientInformation → Default → Primary*
 */
export interface PatientInformationSliceDefaultPrimary {
  /**
   * Title field in *PatientInformation → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Patient Information
   * - **API ID Path**: patient_information.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Request Title field in *PatientInformation → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: patient_information.default.primary.request_title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  request_title: prismic.RichTextField;

  /**
   * Request Link field in *PatientInformation → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: patient_information.default.primary.request_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  request_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Request Description field in *PatientInformation → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: patient_information.default.primary.request_description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  request_description: prismic.RichTextField;

  /**
   * Content Info field in *PatientInformation → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: patient_information.default.primary.content_info
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  content_info: prismic.RichTextField;
}

/**
 * Default variation for PatientInformation Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default variation
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type PatientInformationSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<PatientInformationSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *PatientInformation*
 */
type PatientInformationSliceVariation = PatientInformationSliceDefault;

/**
 * PatientInformation Shared Slice
 *
 * - **API ID**: `patient_information`
 * - **Description**: Patient information section with appointment request details and guidelines
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type PatientInformationSlice = prismic.SharedSlice<
  "patient_information",
  PatientInformationSliceVariation
>;

/**
 * Item in *PatientStories → Default → Primary → Testimonials*
 */
export interface PatientStoriesSliceDefaultPrimaryTestimonialsItem {
  /**
   * Video Thumbnail field in *PatientStories → Default → Primary → Testimonials*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: patient_stories.default.primary.testimonials[].video_thumbnail
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  video_thumbnail: prismic.ImageField<never>;

  /**
   * Video Link field in *PatientStories → Default → Primary → Testimonials*
   *
   * - **Field Type**: Embed
   * - **Placeholder**: *None*
   * - **API ID Path**: patient_stories.default.primary.testimonials[].video_link
   * - **Documentation**: https://prismic.io/docs/fields/embed
   */
  video_link: prismic.EmbedField;
}

/**
 * Primary content in *PatientStories → Default → Primary*
 */
export interface PatientStoriesSliceDefaultPrimary {
  /**
   * Title field in *PatientStories → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Section title
   * - **API ID Path**: patient_stories.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Testimonials field in *PatientStories → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: patient_stories.default.primary.testimonials[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  testimonials: prismic.GroupField<
    Simplify<PatientStoriesSliceDefaultPrimaryTestimonialsItem>
  >;

  /**
   * Description field in *PatientStories → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: patient_stories.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;
}

/**
 * Default variation for PatientStories Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default patient stories variation
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type PatientStoriesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<PatientStoriesSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *PatientStories*
 */
type PatientStoriesSliceVariation = PatientStoriesSliceDefault;

/**
 * PatientStories Shared Slice
 *
 * - **API ID**: `patient_stories`
 * - **Description**: A section displaying patient testimonial videos with a section title
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type PatientStoriesSlice = prismic.SharedSlice<
  "patient_stories",
  PatientStoriesSliceVariation
>;

/**
 * Item in *MessageSection → With Buttons → Primary → CTA Buttons*
 */
export interface QualityCareMessageSliceWithButtonsPrimaryCtaButtonsItem {
  /**
   * Action field in *MessageSection → With Buttons → Primary → CTA Buttons*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: quality_care_message.withButtons.primary.cta_buttons[].action
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  action: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Primary content in *MessageSection → Default → Primary*
 */
export interface QualityCareMessageSliceDefaultPrimary {
  /**
   * Heading field in *MessageSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Enter heading
   * - **API ID Path**: quality_care_message.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Description field in *MessageSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Enter description
   * - **API ID Path**: quality_care_message.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;
}

/**
 * Default variation for MessageSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default variation
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type QualityCareMessageSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<QualityCareMessageSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *MessageSection → With Media → Primary*
 */
export interface QualityCareMessageSliceWithMediaPrimary {
  /**
   * Heading field in *MessageSection → With Media → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Enter heading
   * - **API ID Path**: quality_care_message.withMedia.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Description field in *MessageSection → With Media → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Enter description
   * - **API ID Path**: quality_care_message.withMedia.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Media Content field in *MessageSection → With Media → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: quality_care_message.withMedia.primary.media_content
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  media_content: prismic.RichTextField;
}

/**
 * With Media variation for MessageSection Slice
 *
 * - **API ID**: `withMedia`
 * - **Description**: Default variation
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type QualityCareMessageSliceWithMedia = prismic.SharedSliceVariation<
  "withMedia",
  Simplify<QualityCareMessageSliceWithMediaPrimary>,
  never
>;

/**
 * Primary content in *MessageSection → With Buttons → Primary*
 */
export interface QualityCareMessageSliceWithButtonsPrimary {
  /**
   * Heading field in *MessageSection → With Buttons → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Enter heading
   * - **API ID Path**: quality_care_message.withButtons.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Description field in *MessageSection → With Buttons → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Enter description
   * - **API ID Path**: quality_care_message.withButtons.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * CTA Buttons field in *MessageSection → With Buttons → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: quality_care_message.withButtons.primary.cta_buttons[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  cta_buttons: prismic.GroupField<
    Simplify<QualityCareMessageSliceWithButtonsPrimaryCtaButtonsItem>
  >;
}

/**
 * With Buttons variation for MessageSection Slice
 *
 * - **API ID**: `withButtons`
 * - **Description**: Default variation
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type QualityCareMessageSliceWithButtons = prismic.SharedSliceVariation<
  "withButtons",
  Simplify<QualityCareMessageSliceWithButtonsPrimary>,
  never
>;

/**
 * Slice variation for *MessageSection*
 */
type QualityCareMessageSliceVariation =
  | QualityCareMessageSliceDefault
  | QualityCareMessageSliceWithMedia
  | QualityCareMessageSliceWithButtons;

/**
 * MessageSection Shared Slice
 *
 * - **API ID**: `quality_care_message`
 * - **Description**: A quality care message section with heading and description
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type QualityCareMessageSlice = prismic.SharedSlice<
  "quality_care_message",
  QualityCareMessageSliceVariation
>;

/**
 * Item in *ReviewsCTA → Default → Primary → Reviews*
 */
export interface ReviewsCtaSliceDefaultPrimaryReviewsItem {
  /**
   * Platform Icon field in *ReviewsCTA → Default → Primary → Reviews*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: reviews_cta.default.primary.reviews[].icon
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  icon: prismic.ImageField<never>;

  /**
   * Review Count field in *ReviewsCTA → Default → Primary → Reviews*
   *
   * - **Field Type**: Text
   * - **Placeholder**: 551+
   * - **API ID Path**: reviews_cta.default.primary.reviews[].count
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  count: prismic.KeyTextField;

  /**
   * Review Description field in *ReviewsCTA → Default → Primary → Reviews*
   *
   * - **Field Type**: Text
   * - **Placeholder**: 5.0-stars Google Reviews
   * - **API ID Path**: reviews_cta.default.primary.reviews[].description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  description: prismic.KeyTextField;
}

/**
 * Primary content in *ReviewsCTA → Default → Primary*
 */
export interface ReviewsCtaSliceDefaultPrimary {
  /**
   * Subheading field in *ReviewsCTA → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Had a Great Experience?
   * - **API ID Path**: reviews_cta.default.primary.subheading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  subheading: prismic.KeyTextField;

  /**
   * Heading field in *ReviewsCTA → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: We'd Love to Hear From You!
   * - **API ID Path**: reviews_cta.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Background Image field in *ReviewsCTA → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: reviews_cta.default.primary.background_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  background_image: prismic.ImageField<never>;

  /**
   * Reviews field in *ReviewsCTA → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: reviews_cta.default.primary.reviews[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  reviews: prismic.GroupField<
    Simplify<ReviewsCtaSliceDefaultPrimaryReviewsItem>
  >;
}

/**
 * Default variation for ReviewsCTA Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default variation of ReviewsCTA slice
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ReviewsCtaSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ReviewsCtaSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ReviewsCTA*
 */
type ReviewsCtaSliceVariation = ReviewsCtaSliceDefault;

/**
 * ReviewsCTA Shared Slice
 *
 * - **API ID**: `reviews_cta`
 * - **Description**: A section showcasing reviews from multiple platforms with counts and descriptions
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ReviewsCtaSlice = prismic.SharedSlice<
  "reviews_cta",
  ReviewsCtaSliceVariation
>;

/**
 * Item in *ReviewsGrid → Default → Primary → Reviews*
 */
export interface ReviewsGridSliceDefaultPrimaryReviewsItem {
  /**
   * Author Avatar field in *ReviewsGrid → Default → Primary → Reviews*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: reviews_grid.default.primary.reviews[].avatar
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  avatar: prismic.ImageField<never>;

  /**
   * Author Name field in *ReviewsGrid → Default → Primary → Reviews*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: reviews_grid.default.primary.reviews[].authorName
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  authorName: prismic.KeyTextField;

  /**
   * Review Date field in *ReviewsGrid → Default → Primary → Reviews*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: reviews_grid.default.primary.reviews[].review_date
   * - **Documentation**: https://prismic.io/docs/fields/date
   */
  review_date: prismic.DateField;

  /**
   * Star Rating field in *ReviewsGrid → Default → Primary → Reviews*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: reviews_grid.default.primary.reviews[].rating
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  rating: prismic.NumberField;

  /**
   * Review Text field in *ReviewsGrid → Default → Primary → Reviews*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: reviews_grid.default.primary.reviews[].reviewText
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  reviewText: prismic.RichTextField;
}

/**
 * Primary content in *ReviewsGrid → Default → Primary*
 */
export interface ReviewsGridSliceDefaultPrimary {
  /**
   * Reviews field in *ReviewsGrid → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: reviews_grid.default.primary.reviews[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  reviews: prismic.GroupField<
    Simplify<ReviewsGridSliceDefaultPrimaryReviewsItem>
  >;

  /**
   * View More Button field in *ReviewsGrid → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: reviews_grid.default.primary.viewMoreLink
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  viewMoreLink: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Default variation for ReviewsGrid Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default variation of ReviewsGrid
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ReviewsGridSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ReviewsGridSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ReviewsGrid*
 */
type ReviewsGridSliceVariation = ReviewsGridSliceDefault;

/**
 * ReviewsGrid Shared Slice
 *
 * - **API ID**: `reviews_grid`
 * - **Description**: A grid of review/testimonial cards displaying customer reviews with avatars, ratings, and testimonial text
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ReviewsGridSlice = prismic.SharedSlice<
  "reviews_grid",
  ReviewsGridSliceVariation
>;

/**
 * Item in *ServiceCard → Default → Primary → Features*
 */
export interface ServiceCardSliceDefaultPrimaryFeaturesItem {
  /**
   * Feature Name field in *ServiceCard → Default → Primary → Features*
   *
   * - **Field Type**: Text
   * - **Placeholder**: e.g., Dental Implants
   * - **API ID Path**: service_card.default.primary.features[].feature_name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  feature_name: prismic.KeyTextField;

  /**
   * Feature Description field in *ServiceCard → Default → Primary → Features*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service_card.default.primary.features[].feature_description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  feature_description: prismic.RichTextField;

  /**
   * Feature Image field in *ServiceCard → Default → Primary → Features*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: service_card.default.primary.features[].feature_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  feature_image: prismic.ImageField<never>;
}

/**
 * Primary content in *ServiceCard → Default → Primary*
 */
export interface ServiceCardSliceDefaultPrimary {
  /**
   * Features field in *ServiceCard → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: service_card.default.primary.features[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  features: prismic.GroupField<
    Simplify<ServiceCardSliceDefaultPrimaryFeaturesItem>
  >;
}

/**
 * Default variation for ServiceCard Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default service card variation
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ServiceCardSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ServiceCardSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ServiceCard*
 */
type ServiceCardSliceVariation = ServiceCardSliceDefault;

/**
 * ServiceCard Shared Slice
 *
 * - **API ID**: `service_card`
 * - **Description**: A service card component displaying a dental service specialty with title, description, features, and image
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ServiceCardSlice = prismic.SharedSlice<
  "service_card",
  ServiceCardSliceVariation
>;

/**
 * Item in *ServicesGrid → Default → Primary → Services*
 */
export interface ServicesGridSliceDefaultPrimaryServicesItem {
  /**
   * Icon field in *ServicesGrid → Default → Primary → Services*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: services_grid.default.primary.services[].icon
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  icon: prismic.ImageField<never>;

  /**
   * Service Title field in *ServicesGrid → Default → Primary → Services*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: services_grid.default.primary.services[].title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Learn More Link field in *ServicesGrid → Default → Primary → Services*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: services_grid.default.primary.services[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Primary content in *ServicesGrid → Default → Primary*
 */
export interface ServicesGridSliceDefaultPrimary {
  /**
   * Heading field in *ServicesGrid → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: services_grid.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Services field in *ServicesGrid → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: services_grid.default.primary.services[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  services: prismic.GroupField<
    Simplify<ServicesGridSliceDefaultPrimaryServicesItem>
  >;

  /**
   * CTA Button field in *ServicesGrid → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: services_grid.default.primary.cta_button
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  cta_button: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Default variation for ServicesGrid Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default variation
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ServicesGridSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ServicesGridSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ServicesGrid*
 */
type ServicesGridSliceVariation = ServicesGridSliceDefault;

/**
 * ServicesGrid Shared Slice
 *
 * - **API ID**: `services_grid`
 * - **Description**: A grid of services with heading, service cards, and CTA button
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ServicesGridSlice = prismic.SharedSlice<
  "services_grid",
  ServicesGridSliceVariation
>;

/**
 * Primary content in *SmileCallout → Default → Primary*
 */
export interface SmileCalloutSliceDefaultPrimary {
  /**
   * Heading field in *SmileCallout → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Enter heading
   * - **API ID Path**: smile_callout.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Featured Image field in *SmileCallout → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: smile_callout.default.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Main Description field in *SmileCallout → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Enter description
   * - **API ID Path**: smile_callout.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Padding Top field in *SmileCallout → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: smile_callout.default.primary.padding_top
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  padding_top: prismic.BooleanField;
}

/**
 * Default variation for SmileCallout Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default variation
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type SmileCalloutSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SmileCalloutSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *SmileCallout*
 */
type SmileCalloutSliceVariation = SmileCalloutSliceDefault;

/**
 * SmileCallout Shared Slice
 *
 * - **API ID**: `smile_callout`
 * - **Description**: Dental consultation callout section with image and description
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type SmileCalloutSlice = prismic.SharedSlice<
  "smile_callout",
  SmileCalloutSliceVariation
>;

/**
 * Item in *TeamSection → Default → Primary → Team Members*
 */
export interface TeamSectionSliceDefaultPrimaryTeamMembersItem {
  /**
   * Member Image field in *TeamSection → Default → Primary → Team Members*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: team_section.default.primary.team_members[].member_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  member_image: prismic.ImageField<never>;

  /**
   * Member Name field in *TeamSection → Default → Primary → Team Members*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: team_section.default.primary.team_members[].member_name
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  member_name: prismic.RichTextField;

  /**
   * Biography field in *TeamSection → Default → Primary → Team Members*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: team_section.default.primary.team_members[].biography
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  biography: prismic.RichTextField;
}

/**
 * Primary content in *TeamSection → Default → Primary*
 */
export interface TeamSectionSliceDefaultPrimary {
  /**
   * Heading field in *TeamSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Meet The Team
   * - **API ID Path**: team_section.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Team Members field in *TeamSection → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: team_section.default.primary.team_members[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  team_members: prismic.GroupField<
    Simplify<TeamSectionSliceDefaultPrimaryTeamMembersItem>
  >;
}

/**
 * Default variation for TeamSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default team section variation
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TeamSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TeamSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *TeamSection*
 */
type TeamSectionSliceVariation = TeamSectionSliceDefault;

/**
 * TeamSection Shared Slice
 *
 * - **API ID**: `team_section`
 * - **Description**: A section displaying team member profiles with photos, bios, and quotes
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TeamSectionSlice = prismic.SharedSlice<
  "team_section",
  TeamSectionSliceVariation
>;

/**
 * Item in *Testimonial → Default → Primary → Testimonials*
 */
export interface TestimonialSliceDefaultPrimaryTestimonialsItem {
  /**
   * Title field in *Testimonial → Default → Primary → Testimonials*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial.default.primary.testimonials[].title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Review Content field in *Testimonial → Default → Primary → Testimonials*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial.default.primary.testimonials[].review_content
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  review_content: prismic.RichTextField;

  /**
   * Reviewer Name field in *Testimonial → Default → Primary → Testimonials*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial.default.primary.testimonials[].reviewer_name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  reviewer_name: prismic.KeyTextField;

  /**
   * Reviewer Image field in *Testimonial → Default → Primary → Testimonials*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial.default.primary.testimonials[].reviewer_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  reviewer_image: prismic.ImageField<never>;
}

/**
 * Primary content in *Testimonial → Default → Primary*
 */
export interface TestimonialSliceDefaultPrimary {
  /**
   * Testimonials field in *Testimonial → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial.default.primary.testimonials[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  testimonials: prismic.GroupField<
    Simplify<TestimonialSliceDefaultPrimaryTestimonialsItem>
  >;

  /**
   * View More Action field in *Testimonial → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial.default.primary.view_more_action
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  view_more_action: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Default variation for Testimonial Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default testimonial variation
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TestimonialSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TestimonialSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Testimonial*
 */
type TestimonialSliceVariation = TestimonialSliceDefault;

/**
 * Testimonial Shared Slice
 *
 * - **API ID**: `testimonial`
 * - **Description**: Customer testimonial section with image, review text, and call-to-action
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TestimonialSlice = prismic.SharedSlice<
  "testimonial",
  TestimonialSliceVariation
>;

/**
 * Primary content in *TreatmentShowcase → Default → Primary*
 */
export interface TreatmentShowcaseSliceDefaultPrimary {
  /**
   * Featured Image field in *TreatmentShowcase → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: treatment_showcase.default.primary.featured_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  featured_image: prismic.ImageField<never>;

  /**
   * Title field in *TreatmentShowcase → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: treatment_showcase.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Description field in *TreatmentShowcase → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: treatment_showcase.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Video Embed field in *TreatmentShowcase → Default → Primary*
   *
   * - **Field Type**: Embed
   * - **Placeholder**: *None*
   * - **API ID Path**: treatment_showcase.default.primary.video_embed
   * - **Documentation**: https://prismic.io/docs/fields/embed
   */
  video_embed: prismic.EmbedField;
}

/**
 * Default variation for TreatmentShowcase Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default treatment showcase variation
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TreatmentShowcaseSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TreatmentShowcaseSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *TreatmentShowcase*
 */
type TreatmentShowcaseSliceVariation = TreatmentShowcaseSliceDefault;

/**
 * TreatmentShowcase Shared Slice
 *
 * - **API ID**: `treatment_showcase`
 * - **Description**: A treatment showcase section featuring an image, title, description, and embedded video section
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TreatmentShowcaseSlice = prismic.SharedSlice<
  "treatment_showcase",
  TreatmentShowcaseSliceVariation
>;

/**
 * Item in *VideoCarousel → Default → Primary → Carousel Videos*
 */
export interface VideoCarouselSliceDefaultPrimaryCarouselVideosItem {
  /**
   * Video field in *VideoCarousel → Default → Primary → Carousel Videos*
   *
   * - **Field Type**: Embed
   * - **Placeholder**: *None*
   * - **API ID Path**: video_carousel.default.primary.carousel_videos[].video
   * - **Documentation**: https://prismic.io/docs/fields/embed
   */
  video: prismic.EmbedField;
}

/**
 * Primary content in *VideoCarousel → Default → Primary*
 */
export interface VideoCarouselSliceDefaultPrimary {
  /**
   * Featured Video field in *VideoCarousel → Default → Primary*
   *
   * - **Field Type**: Embed
   * - **Placeholder**: *None*
   * - **API ID Path**: video_carousel.default.primary.featured_video
   * - **Documentation**: https://prismic.io/docs/fields/embed
   */
  featured_video: prismic.EmbedField;

  /**
   * Carousel Videos field in *VideoCarousel → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: video_carousel.default.primary.carousel_videos[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  carousel_videos: prismic.GroupField<
    Simplify<VideoCarouselSliceDefaultPrimaryCarouselVideosItem>
  >;
}

/**
 * Default variation for VideoCarousel Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default variation with featured video and video carousel
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type VideoCarouselSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<VideoCarouselSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *VideoCarousel*
 */
type VideoCarouselSliceVariation = VideoCarouselSliceDefault;

/**
 * VideoCarousel Shared Slice
 *
 * - **API ID**: `video_carousel`
 * - **Description**: A video carousel slice with a featured video and carousel of video thumbnails
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type VideoCarouselSlice = prismic.SharedSlice<
  "video_carousel",
  VideoCarouselSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      FooterDocument,
      FooterDocumentData,
      FooterDocumentDataSocialLinksItem,
      FooterDocumentDataContactsItem,
      FooterDocumentDataNavigationsItem,
      FooterDocumentDataOfficeHoursItem,
      FooterDocumentDataTopFooterContactsItem,
      HeaderDocument,
      HeaderDocumentData,
      HeaderDocumentDataNavigationsItem,
      HeaderDocumentDataCtaButtonsItem,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      AllDocumentTypes,
      CaseShowcaseSlice,
      CaseShowcaseSliceDefaultPrimaryCasesItem,
      CaseShowcaseSliceDefaultPrimary,
      CaseShowcaseSliceVariation,
      CaseShowcaseSliceDefault,
      CertificationsSlice,
      CertificationsSliceDefaultPrimaryCertificationsItem,
      CertificationsSliceDefaultPrimary,
      CertificationsSliceVariation,
      CertificationsSliceDefault,
      ConsultationCtaSlice,
      ConsultationCtaSliceDefaultPrimaryContactsItem,
      ConsultationCtaSliceDefaultPrimaryOfficeHoursItem,
      ConsultationCtaSliceDefaultPrimary,
      ConsultationCtaSliceVariation,
      ConsultationCtaSliceDefault,
      DentalHeroSlice,
      DentalHeroSliceDefaultPrimary,
      DentalHeroSliceVariation,
      DentalHeroSliceDefault,
      DentalImplantGuideSlice,
      DentalImplantGuideSliceDefaultPrimary,
      DentalImplantGuideSliceVariation,
      DentalImplantGuideSliceDefault,
      DoctorProfileSlice,
      DoctorProfileSliceDefaultPrimary,
      DoctorProfileSliceVariation,
      DoctorProfileSliceDefault,
      LargeImageSlice,
      LargeImageSliceDefaultPrimary,
      LargeImageSliceVariation,
      LargeImageSliceDefault,
      MembershipPlansSlice,
      MembershipPlansSliceDefaultPrimaryPlansItem,
      MembershipPlansSliceDefaultPrimary,
      MembershipPlansSliceVariation,
      MembershipPlansSliceDefault,
      OfficeGallerySlice,
      OfficeGallerySliceDefaultPrimaryGalleryImagesItem,
      OfficeGallerySliceDefaultPrimary,
      OfficeGallerySliceVariation,
      OfficeGallerySliceDefault,
      PatientInformationSlice,
      PatientInformationSliceDefaultPrimary,
      PatientInformationSliceVariation,
      PatientInformationSliceDefault,
      PatientStoriesSlice,
      PatientStoriesSliceDefaultPrimaryTestimonialsItem,
      PatientStoriesSliceDefaultPrimary,
      PatientStoriesSliceVariation,
      PatientStoriesSliceDefault,
      QualityCareMessageSlice,
      QualityCareMessageSliceDefaultPrimary,
      QualityCareMessageSliceWithMediaPrimary,
      QualityCareMessageSliceWithButtonsPrimaryCtaButtonsItem,
      QualityCareMessageSliceWithButtonsPrimary,
      QualityCareMessageSliceVariation,
      QualityCareMessageSliceDefault,
      QualityCareMessageSliceWithMedia,
      QualityCareMessageSliceWithButtons,
      ReviewsCtaSlice,
      ReviewsCtaSliceDefaultPrimaryReviewsItem,
      ReviewsCtaSliceDefaultPrimary,
      ReviewsCtaSliceVariation,
      ReviewsCtaSliceDefault,
      ReviewsGridSlice,
      ReviewsGridSliceDefaultPrimaryReviewsItem,
      ReviewsGridSliceDefaultPrimary,
      ReviewsGridSliceVariation,
      ReviewsGridSliceDefault,
      ServiceCardSlice,
      ServiceCardSliceDefaultPrimaryFeaturesItem,
      ServiceCardSliceDefaultPrimary,
      ServiceCardSliceVariation,
      ServiceCardSliceDefault,
      ServicesGridSlice,
      ServicesGridSliceDefaultPrimaryServicesItem,
      ServicesGridSliceDefaultPrimary,
      ServicesGridSliceVariation,
      ServicesGridSliceDefault,
      SmileCalloutSlice,
      SmileCalloutSliceDefaultPrimary,
      SmileCalloutSliceVariation,
      SmileCalloutSliceDefault,
      TeamSectionSlice,
      TeamSectionSliceDefaultPrimaryTeamMembersItem,
      TeamSectionSliceDefaultPrimary,
      TeamSectionSliceVariation,
      TeamSectionSliceDefault,
      TestimonialSlice,
      TestimonialSliceDefaultPrimaryTestimonialsItem,
      TestimonialSliceDefaultPrimary,
      TestimonialSliceVariation,
      TestimonialSliceDefault,
      TreatmentShowcaseSlice,
      TreatmentShowcaseSliceDefaultPrimary,
      TreatmentShowcaseSliceVariation,
      TreatmentShowcaseSliceDefault,
      VideoCarouselSlice,
      VideoCarouselSliceDefaultPrimaryCarouselVideosItem,
      VideoCarouselSliceDefaultPrimary,
      VideoCarouselSliceVariation,
      VideoCarouselSliceDefault,
    };
  }
}
