// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  certifications: dynamic(() => import("./Certifications")),
  dental_hero: dynamic(() => import("./Hero")),
  large_image: dynamic(() => import("./LargeImage")),
  quality_care_message: dynamic(() => import("./MessageSection")),
  services_grid: dynamic(() => import("./ServicesGrid")),
  testimonial: dynamic(() => import("./Testimonial")),
};
